---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job-db-settings.yaml

labels:
  - pairs:
      app.kubernetes.io/component: jobs
      app.kubernetes.io/part-of: dataverse
      app.kubernetes.io/managed-by: fluxcd