---
apiVersion: v1
kind: Service
metadata:
  name: dataverse
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector: {} # kustomize will take care of this!
