---
# DO NOT COMMIT THIS FILE TO VERSION CONTROL ONCE YOU ADDED YOUR PAT
apiVersion: v1
kind: Secret
metadata:
  name: github-pat
  namespace: flux-system
type: Opaque
stringData:
  # Any username string is fine with GitHub (YMMV)
  username: git
  # Replace this with your actual GitHub Personal Access Token
  password: supersecret123
