apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - ../../../student/base

# Keep in sync with namespace.yml or else!!!
namespace: washere-prod

labels:
  - pairs:
      app: washere
      env: prod
    includeSelectors: true

patches:
  - target: { kind: Deployment, name: washere }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target: { kind: Ingress, name: washere }
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: washere.ct.gdcc.io